# Generated by Django 3.1.7 on 2021-03-05 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('tracking_number', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('receiver', models.CharField(max_length=300)),
                ('signed_for_by', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Sold'), (1, 'Remaining')], default=1)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
