# Generated by Django 3.1.7 on 2021-03-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210305_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
        ),
    ]
