# Generated by Django 3.1.7 on 2021-03-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210305_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.IntegerField(choices=[(0, 'NIL'), (1, 'Delivered')], default=1),
        ),
    ]
